using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class StandardLevelHp_V1 : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new StandardLevelHp_V1(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new StandardLevelHp_V1(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4631214383819485451UL,14296397991668860046UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name => _f_name[Index];
	public System.Int32 f_Lv => _f_Lv[Index];
	public System.Single f_Hp => _f_Hp[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5679202159330429867UL, 2813791299601038014UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Lv;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Lv => _ufle12jhs77_f_Lv ?? (_ufle12jhs77_f_Lv = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5145158177750461370UL, 17453427529155412101UL), () => _ufle12jhs77_f_Lv = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Hp;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Hp => _ufle12jhs77_f_Hp ?? (_ufle12jhs77_f_Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5606005820435435437UL, 4033191549190676628UL), () => _ufle12jhs77_f_Hp = null));
	private static readonly StandardLevelHp_V1.Factory _factory0_PFS = new StandardLevelHp_V1.Factory();
	private static readonly StandardLevelHp_V2.Factory _factory1_PFS = new StandardLevelHp_V2.Factory();
	private StandardLevelHp_V1() : base(MetaDefault) {}
	private StandardLevelHp_V1(BGId id) : base(MetaDefault, id) {}
	private StandardLevelHp_V1(BGMetaEntity meta) : base(meta) {}
	private StandardLevelHp_V1(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static StandardLevelHp_V1 FindEntity(Predicate<StandardLevelHp_V1> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<StandardLevelHp_V1> FindEntities(Predicate<StandardLevelHp_V1> filter, List<StandardLevelHp_V1> result=null, Comparison<StandardLevelHp_V1> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<StandardLevelHp_V1> action, Predicate<StandardLevelHp_V1> filter=null, Comparison<StandardLevelHp_V1> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static StandardLevelHp_V1 GetEntity(BGId entityId) => (StandardLevelHp_V1) MetaDefault.GetEntity(entityId);
	public static StandardLevelHp_V1 GetEntity(int index) => (StandardLevelHp_V1) MetaDefault[index];
	public static StandardLevelHp_V1 GetEntity(string entityName) => (StandardLevelHp_V1) MetaDefault.GetEntity(entityName);
}

public partial class StandardLevelHp_V2 : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new StandardLevelHp_V2(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new StandardLevelHp_V2(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5612857040481795970UL,1584007360142949784UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name => _f_name[Index];
	public System.Int32 f_Lv => _f_Lv[Index];
	public System.Single f_Hp => _f_Hp[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5437770401305036474UL, 9264638420802151850UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Lv;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Lv => _ufle12jhs77_f_Lv ?? (_ufle12jhs77_f_Lv = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5689629695358655917UL, 1070279503486329472UL), () => _ufle12jhs77_f_Lv = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Hp;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Hp => _ufle12jhs77_f_Hp ?? (_ufle12jhs77_f_Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5173763733506237311UL, 9338054821098045086UL), () => _ufle12jhs77_f_Hp = null));
	private static readonly StandardLevelHp_V1.Factory _factory0_PFS = new StandardLevelHp_V1.Factory();
	private static readonly StandardLevelHp_V2.Factory _factory1_PFS = new StandardLevelHp_V2.Factory();
	private StandardLevelHp_V2() : base(MetaDefault) {}
	private StandardLevelHp_V2(BGId id) : base(MetaDefault, id) {}
	private StandardLevelHp_V2(BGMetaEntity meta) : base(meta) {}
	private StandardLevelHp_V2(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static StandardLevelHp_V2 FindEntity(Predicate<StandardLevelHp_V2> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<StandardLevelHp_V2> FindEntities(Predicate<StandardLevelHp_V2> filter, List<StandardLevelHp_V2> result=null, Comparison<StandardLevelHp_V2> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<StandardLevelHp_V2> action, Predicate<StandardLevelHp_V2> filter=null, Comparison<StandardLevelHp_V2> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static StandardLevelHp_V2 GetEntity(BGId entityId) => (StandardLevelHp_V2) MetaDefault.GetEntity(entityId);
	public static StandardLevelHp_V2 GetEntity(int index) => (StandardLevelHp_V2) MetaDefault[index];
	public static StandardLevelHp_V2 GetEntity(string entityName) => (StandardLevelHp_V2) MetaDefault.GetEntity(entityName);
}
#pragma warning restore 414
